name: islami
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_compass: ^0.8.1
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  readmore: ^3.0.0
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/files/
    - assets/files/azkar/
    - assets/fonts/

  fonts:
    - family: QuranFont
      fonts:
        - asset: assets/fonts/خط القرآن القلم.ttf
    - family: NoorHuda
      fonts:
        - asset: assets/fonts/خط نور الهدى.ttf
    - family: QuranHadith
      fonts:
        - asset: assets/fonts/خط قران حديث.ttf
